### ISSUE TITLE
Nice-to-have posters and cards

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#158]
Using this ticket to capture posters and other design elements that are not part of the MVP. These could be done by staff/volunteers on Friday and throughout the weekend.
- [ ] Welcome signs in other languages #203 
- [ ] Thank you for coming sign (multi-lingual would be rad) like @flukeout's [beauty from 2015](https://www.flickr.com/photos/mozfest/22894036881/in/album-72157658649418943/)  #204
- [ ] Handwritten thank you cards for key festival contributors #205
- [ ] ~~Postcard "hello from MozFest" inspired by the ultra cool [Michelberger hotel info pack](https://github.com/MozillaFoundation/Mozfest2016_production/issues/19)~~

**Comment by SpikeUK** [comment]
There was also a thank you card _from_ the attendees in 2015
![imag0884](https://cloud.githubusercontent.com/assets/1629474/18793796/5993a676-81b4-11e6-8bd0-b675128c33f0.jpg)

**Comment by edrushka** [comment]
For the multi-lingual nice-to-haves, here is the spreadsheet showing the [multi-lingual sessions so far](https://docs.google.com/spreadsheets/d/1xyliCPNWNRBAOsDMF4xvojInMkZUD7jQQpEe7bTZ5UM/edit#gid=0)

The most common non-EN language is **Spanish** followed by **French**. If we have limited bandwidth for multi-lingual nice-to-have design, I would prioritize those two.

**Comment by edrushka** [comment]
@kristinashu the order of the assets in the first comment is the priority order. I can make individual tickets if you like. 

What are your thoughts on the post-card? As much as I love the idea, I'm not sure how we share these other than clipping with the festival guide (which was never part of the plan). 

Also - I am absolutely to open to ideas from the design team!!

**Comment by kristinashu** [comment]
@edrushka yes, separate tickets would be great!

I can't really image people using postcards, but maybe that's just me. Also, sounds like advocacy will have postcards related to their post-crimes campaign.

**Comment by kristinashu** [comment]
cc @sabrinang
