### ISSUE TITLE
Prepare graphics for ProPresenter

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#214]
This is very similar to #206. We will be using ProPresenter to highlight individual Tweets and IG posts. We need a few background graphics.

Please prepare:
- [x] muted static background with no additional graphics (same as #206)
- [x] PNG or vector version of logo & wordmark (same as #206)
- [x] PNG or vector version of One Web circle (white/clear circle version) (same as #206)
- [x] PNG or vector version of gear icon on its own (same as #206)
- [x] PNG or vector version of the word #MozFest in our font (with the hashtag)
- [x] link to our festival font

Can you please put all of these in one place and email them to me? I'll pass them on to the stage crew and cc you in case they have questions. Kindly provide by tomorrow afternoon. Thanks! 🌹 

cc @kristinashu @xmatthewx

**Comment by kristinashu** [comment]
Sent in an email with all the assets: https://www.dropbox.com/sh/xpbuxp7iwajnm7d/AADnIjIzvTuE7COSLwMcWR5Wa?dl=0

**Comment by sabrinang** [comment]
## Post MozFest Documentation

The ProPresenter screens showcased #mozfest experience tweets on two large displays on either side of the main stage on level 4. It was seen during Saturday's opening session and welcome notes. Throughout the festival, the monitors continued to display the feed of tweets.

![mozfest-documentation-photos_propresenter-social](https://cloud.githubusercontent.com/assets/2492510/20118446/4e1a1112-a5b9-11e6-9bfb-1bf9ea8856be.png)
