### ISSUE TITLE
Equipment / AV Supplier

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#22]
Looking for an equipment / AV supplier for the main stage AV and architectural lighting on Level 4. 

We require:
- (Equipment list to follow)

**To-Do**
- [x] Equipment list finalised
- [x] List sent to MV Event AV Team
- [x] UK Suppliers Researched and Quotes Received
- [ ] Booking Confirmation and Contract Drawn Up

**Comment by marcwalsh-zz** [comment]
We're working with SLX this year, who is Ravensbourne's preferred supplier. Quotes received, Mac is contacting them and I have a site meeting this Friday to discuss finer details.

**Comment by SpikeUK** [comment]
Does this include the large displays for Science Fair/Demo Party plus info desks Marc?
