### ISSUE TITLE
Live Stream of Main Stage and D&D Spaces

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#25]
Main Stage and D&D talks will be live streamed to AirMozilla.

**To-Do**
- [x] Find Supplier - #24 
- [x] Decision on platform. AirMo / YouTube / Facebook (Both live or YT / FB uploaded later)
- [x] Talk to Ravensbourne Network Manager re: encoder.
- [ ] Player page for website (needed?)

**Comment by edrushka** [comment]
Updates
- Platform is Facebook.
- Website will link to Facebook (no live embedding, it will be a simple link)
