### ISSUE TITLE
Swag - Festival Guide 

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#39]
Design and Print the Festival Guide for 2016.

Format and design TBC

Responsible - MoFo / Contractor

ToDo:
- [x] Confirm printers and deadlines
- [x] Key Design Elements - Front Cover, Layout and Style
- [x] General Content Layout
- [x] Space Icons
- [x] Wayfinding (Maps / Floorplans)

Some inspiration is available **[here](https://drive.google.com/open?id=0BymL-b3rLMtZcHFRaENZQ3NiNWM)**, feel free to add more!

Sarah has created issue #19 about creating legacy using the Festival Guide. It also has a great example of a series of postcards used by a hotel, which would make printing last minute info so much easier!

**Comment by kristinashu** [comment]
Design is all done https://github.com/MozillaFoundation/Mozfest2016_production/issues/136

These are Single pages, 3mm bleed with crop marks and high quality. The colours are CMYK with Pantone Reflex Blue.

Files are here:
Main Festival Guide - PDF labeled with FINAL 14:10:16 SINGLES
https://drive.google.com/drive/folders/0BzVQTTEXQZdXWC0xbVJuNkpkRTQ

Wrangler Booklet - PDF labeled with FINAL SINGLES
https://drive.google.com/drive/folders/0BzVQTTEXQZdXMlh0Rm1YR1cwZ3M

**Comment by kristinashu** [comment]
I things this is all done, @marcwalsh please reopen this ticket if you still need it.
