### ISSUE TITLE
Production team plan - this heartbeat and beyond

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#40]
This issue captures Mozfest production planning meeting, identifies open questions, and lists deliverables for this heartbeat (please file individual tickets for your tasks). 

### Roles and responsibilities

- [x] Divvy up the broad tasks
   - Go Global: 
     - Look and Feel + theme 
     - Website
   - Connecting Leaders:
     - Event experience / space
     - Schedule app / proposals
     - Supporting the hiring of a contractor 
- [x] Clarify PM roles with @edrushka, @xmatthewx, @hannahkane. To discuss: MW and HK are hoping ED will drive - schedule / facilitate meetings :) - MEETING SCHEDULED FOR FRIDAY

### Deliverables for this heartbeat
   - [x] Look & Feel (@sabrinang / Go Global to lead)
     - [x] Establish possible directions (present existing images found online) https://github.com/MozillaFoundation/Mozfest2016_production/issues/41
     - [x] Connect with Erika & Sarah to identify the theme (maybe 2 heartbeats to finalize) https://github.com/MozillaFoundation/Mozfest2016_production/issues/44
     - [x] Begin styleguide (avoid aspects of the guide that don't actually advance Mozfest design) https://github.com/MozillaFoundation/Mozfest2016_production/issues/42
   - [x] Website - @mmmavis to onboard @alanmoo https://github.com/MozillaFoundation/Mozfest2016_production/issues/43
   - [x] Hiring a contractor (@kristinashu / Connecting Leaders to lead)
     - [x] @sabrinang/@kristinashu - first pass of reviewing candidates from Marc. Schedule Interviews. #23
     - [x] @kristinashu @xmatthewx @edrushka  - begin draft scope of work #12

**Comment by marcwalsh** [comment]
@xmatthewx - When is the meeting on Friday, would it help if I jump in on it also?

**Comment by xmatthewx** [comment]
Probably so @marcwalsh. It's currently scheduled for 2:30pm EDT, which might be too late for you.

**Comment by edrushka** [comment]
@marcwalsh I'll schedule something for next week for a London-friendly time.

**Comment by marcwalsh** [comment]
That would be awesome, I wouldn't be able to make 2:30EDT today. :)

**Comment by xmatthewx** [comment]
Items in this meta ticket have been completed or filed. Closing this.
