### ISSUE TITLE
MoFo dev & design plan for Aug 19 Heartbeat

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#57]
Here's what we'll do this heartbeat:
#### MozFest Look & Feel ( Sabrina / Go Global to lead)
- [x] Week one is expansive. Create application examples (stage design and festival guide cover design) using our chosen moodboard. (Sabrina)
- [x] Week two we'll contract.  Converge ideas and get closer to refined direction. Next heartbeat we'll document and apply to other key assets (Sabrina)
- [x] Scope Festival Guide (design team + Sarah, Erika and Marc W.) #58
- next heartbeat, apply a few elements to Festival guide (e.g. integrating space icons, page numbers, fonts/headers, photo treatments)
#### Hire Junior Design Contractor ( Kristina / Connecting Leaders to lead)
- [x] Conduct interviews (Kristina) #47 
- [ ] ~~Re-post if required (Marc W.)~~
- [x] Give ops a heads up to prepare contract (Sarah) #59
#### Website (Erika to lead)
- [x] Meet with Mark S. on Wed Aug 10 (Sarah, Erika Matthew)
- ~~File new tickets based on this convo (Erika)~~
- [x] Update timings page [Ticket here](https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/78) (Alan) 
- [ ] Start collecting Space Wrangler bios (Erika, Sarah, Marc W.) #54
#### Schedule App (Matthew to lead)
- [x] Conclude 3rd party tool conversation (Matthew) [Ticket here](https://github.com/mozilla/schedule-app-core/issues/220#issuecomment-237400492)
- [ ] Review estimates, plan roadmap (Mavis and Matthew) [Ticket here](https://github.com/mozilla/schedule-app-core/issues/235)

**Comment by edrushka** [comment]
cc @xmatthewx @hannahkane @sabrinang @kristinashu @alanmoo @mmmavis @Saallen @marcwalsh

**Comment by hannahkane** [comment]
@edrushka - okay to close this ticket?
