### ISSUE TITLE
MoFo comms & marketing plan for Aug 19 Heartbeat

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#60]
Similar to #57 I'm going to start writing meta-tickets for our comms and marketing work to keep track of a few pieces. Let me know if these are annoying!

Here's what we'll do this heartbeat:
#### D&D ( Kevin to lead)
- [x] Meet with MoCo to discuss D&D videos post-festival #53 (Erika, Kevin & Paul)
- [x] Present Mark S. with 2 options for spaces #51 (Kevin)
- [ ] Upon Mark's approval, inform Todo to incorporate all or part of their installation (Erika) 
- [x] Send D&D speaker invites (Kevin to coordinate invites from Mark, Brett and Alex S)
#### Marketing (Paul to lead)
- [x] Write individual tickets after we get the green light (Erika)
- [ ] Meet with Rizwan to align on language and identifying influencers (Erika to coordinate) #61
- [ ] Identify a list of 500 “must-have” attendees (Paul w/input from MLN) #62
- [ ] Draft personal outreach appeals for email and social (Paul)
- [x] Identify select partners for social & email promotion (Sarah to identify)
#### Emails (Kristina to lead)
- [x] Send Aug 10 email (CTA =Ticket sales, send to all)
- [ ] Send Aug 17 email (MoCos only, Expectations)
- [x] Send Aug 17 email (MoFo staff, Travel & expectations)
- [x] Plan post-festival emails #64
#### Social (Kristina to lead)
- [x] Twitter and FB posts according to the [social calendar](https://docs.google.com/spreadsheets/d/1W9O30WNK1BLWfqj-DjkZs_0k0gYq4hMAlrVUWTdJDco/edit#gid=0)

**Comment by edrushka** [comment]
cc @Saallen @KevZawacki @HPaulJohnson @KGorr @marcwalsh

**Comment by KevZawacki** [comment]
Our two space proposals are in front of Mark. I've also requested he begin sending out invites. Will keep all posted!

**Comment by edrushka** [comment]
Walker Space confirmed as home for D&Ds. Asked Paul & Sam to talk to Todo about housing their installation there.
