### ISSUE TITLE
Festival Guide content 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#68]
This is the meta-bug for collecting the MozFest 2016 Festival Guide content

**Comment by edrushka** [comment]
Timings/schedule for Saturday and Sunday: #70

**Comment by edrushka** [comment]
Festival Guide design brief is [here](https://docs.google.com/document/d/1Cz3kZSrwmvnaO8GDlTl8VTcvPjZ4TmjfVvaul8rhOvQ/edit#).

**Content to include:**
- [x] Introduction: What is MozFest? #108_
- [x] Key festival timings #109
- [x] Mozilla’s 5 Key Issues #110 
- [x] Dialogue and Debate Speakers Series - Revisions in #172
- [x] Spaces #112 
- [x] Space wrangler bios #56 
- [x] Non-EN sessions #113  
- [x] Participation guidelines #114
- [x] Network celebration/testimonial piece #115 
- [x] Ravensbourne page #152 
- [x] MozRetreat page #153

**Comment by Saallen** [comment]
Hey @edrushka 
We should have a page about Ravensbourne-
I know we are moving but we still need to acknowledge our relationship, our academic sponsorship and the venue.

**Comment by marcwalsh-zz** [comment]
Hey @edrushka - Just had a thought (it may be too late now)! Would it be worth adding a piece about MozRetreat in Berlin and how that influenced and help shape the festival this year?

**Comment by edrushka** [comment]
Ohhhh that's interesting, Marc. @kristinashu how are we doing for length/pages? Can we add these two pages?

**Comment by kristinashu** [comment]
I believe Carrie-ann has a very rough estimate of 16-20 pages, which is getting pretty long. Unless it's crucial, we should refrain from adding more content 😬

**Comment by edrushka** [comment]
@Saallen now that we have a partners section added to the team page on the website where we can highlight and thank Ravensbourne, do we still need a page for them in the Festival Guide?

**Comment by Saallen** [comment]
@edrushka  Yes as per our relationship they should be added to the festival guide

**Comment by marcwalsh-zz** [comment]
Hey @kristinashu @edrushka - Just wondering if we have a total amount of pages for the festival guide? I've got quotes ranging for 16pp, 20pp and 48pp. 

Would be great to know so I can get a cost confirmed. :)

**Comment by kristinashu** [comment]
The main booklet is 16pp but I'm not sure how many pages the yellow wrangler insert would be? @carrie-ann do you know?

**Comment by Carrie-ann** [comment]
@kristinashu @marcwalsh The wrangler section at the moment is 12pp.

Do you guys need me to share the thoughts on material and binding for the guide to get a quote? It would be the file we spoke through yesterday and I have it here on red pen. 

https://redpen.io/koadf1c145d1a33643

**Comment by marcwalsh-zz** [comment]
@kristinashu @Carrie-ann does the 16pp include the cover?

**Comment by Carrie-ann** [comment]
@marcwalsh @kristinashu  Nope, the cover is currently separate (4pp including inside cover). I envisioned the cover would be a different stock, something with a bit more weight than the internal pages (not too heavy though).

**Comment by xmatthewx** [comment]
@edrushka – I posted some comments about content in Redpen. @kristinashu suggests that we move that discussion to this thread to resolve things before handing it back to Carrie.

**Comment by edrushka** [comment]
+1 to consolidating feedback. I'm swamped but will look at the redpen again as soon as I can. Feel free to book a chat now if you anticipate questions we won't be able to resolve on Github.
