### ISSUE TITLE
MoFo comms & marketing plan for Sept 2 Heartbeat

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#83]
Here's what we'll do this heartbeat:
#### D&D ( Kevin to lead)
- [x] gather next steps for confirmed speakers
- [ ] determine vendor for live-streaming (Marc #24)
#### Marketing (Paul to lead)
- [x] Meet with Rizwan to align on language and identifying influencers (Erika to coordinate) #61
- [ ] Identify a list of 500 “must-have” attendees (Paul) #62
- [ ] Send request to MLN for influencers (Paul)
- [ ] Draft personal outreach appeals for email and social (Paul)
#### Festival Guide (Erika to lead)
- [ ] Gather Space Wrangler Bios #56 
- [x] File individual tickets for each written element of guide
#### Emails
- [x] Send Aug 24 email (DEG to send. Erika coordinating)
- [x] Revise and send MoCo email(s) (Erika and Claw)
#### Social (Kristina to lead)
- [x] Twitter and FB posts according to the [social calendar](https://docs.google.com/spreadsheets/d/1W9O30WNK1BLWfqj-DjkZs_0k0gYq4hMAlrVUWTdJDco/edit#gid=0)

**Comment by edrushka** [comment]
cc @KevZawacki @HPaulJohnson @Saallen @marcwalsh @KGorr
