### ISSUE TITLE
MoFo dev & design plan for Sept 2 Heartbeat

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#98]
Here's what we'll do this heartbeat:
#### MozFest Look & Feel ( Sabrina / Go Global to lead)
- [x] Produce style guide #76
- [ ] Produce a few different hi-res background patterns
- [x] Begin to apply a few design elements to Festival guide (contractors to take over)
- [ ] Begin to apply a few design elements to stage design (contractors to take over)
- [x] Get signoff on design from Sarah (Erika)
- [x] Get signoff on tagline-design combo from Claw (Sarah & Erika)
- [x] Research Festival Guide formats 
#### Hire Junior Design Contractor ( Kristina / Connecting Leaders to lead)
- [x] Finalize contracts (Sarah)
- [x] Develop onboarding plan #82 
#### Website (Erika to lead)
- [x] Meet with Hannah, Wex & Kevin to scope
- [x] Review plan with Sarah
- [x] Write individual tickets to begin design next heartbeat
- [ ] Collecting Space Wrangler bios (Erika, Sarah, Marc W.) #54
#### Schedule App (Kristina to lead this heartbeat since MW is on PTO)
- [ ] UI refresh [tickets here](https://github.com/mozilla/schedule-app-core/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22September+2%2C+2016%22+label%3ADesign)
- [ ] Clarify workflow between spreadsheet, github, staff, and wranglers [ticket here](https://github.com/mozilla/schedule-app-core/issues/238)

**Comment by edrushka** [comment]
cc @sabrinang @kristinashu @hannahkane @Saallen @marcwalsh @mmmavis
